version: '{build}'

environment:
  pdftexify_cp1251:
    texify --pdf --src-specials --tex-option="--src -src-specials --tcx=CP1251 --shell-escape --enable-write18" --batch --tex-option=--interaction=nonstopmode --tex-option=--synctex=-1

cache:
  - c:\miktex -> .\appveyor-miktex-install\miktex-install.bat

install:
  - git submodule update --init --recursive --force
  - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin"
  - cd .\appveyor-miktex-install
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe .\miktex-install.bat
  - cd ..

build_script:
  - '%pdftexify_cp1251% report.tex'

artifacts:
  - path: 'report.pdf'